config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 
  # ユーザの登録フォームを作成するため、newアクションを設定]
  # onlyを指定することで、特定のアクションのルーティングのみ作成

   #  form_withを使用するにはルーティングにcreateアクションを追加
   #  ユーザ登録後に遷移させるためルーティングにshowアクションを追加
   resources :users, only: [:new, :create, :show]

   # ログイン機能のSessionsコントローラ用のルーティング
   # destroyはSessionsコントローラにログアウトを行うためのdestroyアクション
   resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }#presence: true⇛name属性は必ず入力
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  # 大文字と小文字の区別をなくす
  before_validation { email.downcase! }

  # パスワードをハッシュ化
  has_secure_password

    # 省パスワードにバリデーションを設定
    validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #SessionsコントローラでしかSessionsHelper 内のメソッドを呼び出せない
  #すべてのコントローラで利用できるようSessionHelperをインクルード
  include SessionsHelper
  
  # すべてのコントローラのアクションが実行される前に必ず login_required メソッドが呼び出される
  before_action :login_required

  private # 外部から直接呼び出されないようにする
  # ログインしなければアクセスできないよう制限
  def login_required
    # current_userがnilの場合、ログイン画面に遷移させることで、未ログインのユーザからのアクセスを禁止
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #
  #
  skip_before_action :login_required, only: [:new, :create]
  #
  def new 
    #セッションに関してはインスタンスの作成が必要ないので、newアクションには何も処理が入りません
  end

  # Sessionsコントローラにセッションを作成する
  def create
    #入力されたメールアドレスを元に、find_byメソッドを使ってデータベースからユーザを取り出す
    user = User.find_by(email: params[:session][:email].downcase)

    # メールアドレスとパスワードの組み合わせが有効か調べる
    # find_byで取得したユーザのパスワードと引数に指定したパスワードが一致するかを検証
    # params[:session][:password]で入力されたパスワードを取得
    # &.を利用し、nilの場合でもエラーが発生しないようにします
    if user&.authenticate(params[:session][:password])
      # ログイン成功した場合
      # セッションオブジェクトにユーザIDを登録し、そのユーザの詳細画面に遷移
      log_in(user)

      redirect_to user_path(user.id)
    else
      # ログイン失敗した場合
      # renderを使ってnewアクションを呼び出します。
      # 現在のリクエストの間だけメッセージを保持
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  # Sessionsコントローラにログアウトを行う
  def destroy
    session.delete(:user_id) # セッションオブジェクトからユーザIDを削除

    #ログアウトした際は、ログインページに遷移させ、Flashを表示させる
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ユーザーが未ログインの状態でアクセス可能なページを設定
  # ユーザー登録用のnewやcreateアクションではlogin_requiredメソッドが実行されないように設定
  skip_before_action :login_required, only: [:new, :create]

  # showアクションが呼ばれた際、correct_userメソッドを先に実行する
  before_action :correct_user, only: [:show]

  #
  def new
    #新しいUserモデルのインスタンスを作成し、登録フォームで使用できるようにします。
    @user = User.new
  end

   # 
   def create
      @user = User.new(user_params)#登録フォームの入力値を持つインスタンスを作成し、@userに入る
      if @user.save
        # log_in(user)メソッドをユーザが登録された際に呼び出すことで、ログインも同時に行うことができます
        log_in(@user)
        # ユーザ登録に成功した場合の処理
        redirect_to user_path(@user.id)
      else
        puts @user.errors.full_messages # エラーメッセージをコンソールに表示
        # ユーザ登録に失敗した場合の処理:再び登録画面が表示
        render :new
      end
   end
  
      #パラメータに含まれるidを使ってユーザを特定することで、そのユーザの詳細画面を表示
      def show
        @user = User.find(params[:id])
      end
   #登録フォームの入力値は、ストロングパラメータparamsを使って取得
   
   
   private

   def user_params
     params.require(:user).permit(:name, :email, :password, :password_confirmation)
   end

  # 本人しか詳細画面にアクセスできないよう制限を追加
  def correct_user
    @user = User.find(params[:id])
    # パラメータのidを使ってデータベースからユーザを取り出し、current_user?メソッドの引数に渡すことで、アクセス先が本人のものか確認しています。
    # 本人ではなかった場合、そのユーザの詳細画面に遷移させます。
    redirect_to current_user unless current_user?(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
# ヘルパーモジュール（SessionsHelper）は通常、その名前に対応するビューとコントローラでのみ自動的に利用できるように設計されています。
module SessionsHelper
  # ログイン中のユーザ情報を取得
  def current_user
  @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  
  #  
  def logged_in? #メソッド名に?を指定した場合、そのメソッドは真偽値を返す
  current_user.present?
  end

  # ユーザ登録した際にログインも同時に実行される
  # このメソッドをユーザが登録された際に呼び出すことで、ログインも同時に行うことができます
  def log_in(user)
  # セッションオブジェクトを使って、現在ログインしているユーザーのIDをセッションに保存
  session[:user_id] = user.id
  end

  # ログイン中のユーザであれば、他のユーザの詳細画面を閲覧することができてしまいます
  # それを防ぐために本人しか詳細画面にアクセスできないよう制限を追加
  def current_user?(user)
    user == current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>SessionLogin</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%# Flashメッセージをヘッダーに表示させる %>
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

  <%# ログイン画面やユーザ登録画面へ遷移させるためのヘッダーリンクを作成 %>
  <% if logged_in? %>
  <%# ログイン済みの場合は、ログインしているユーザの詳細ページとログアウトへのリンクを表示する %>
  <%= link_to "Profile", user_path(current_user.id) %>
  <%= link_to "Logout", session_path(current_user.id), method: :delete %>
  <% else %>
  <%# 未ログインの場合は、ログインとユーザ登録へのリンクを表示させ、 %>
  <%= link_to "Sign up", new_user_path %>
  <%= link_to "Login", new_session_path %>
  <% end %>

  <%= yield %>
</body>

</html>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%# フォームが表示される前にエラーメッセージを表示するためform_withの前に書く %>
<% if @user.errors.any? %>

<%# Railsがデフォルトで用意しているエラー用のスタイル（CSS）を適用 %>
  <div id="error_explanation">
    
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>